export const countriesCode = [{"Country":"AFGHANISTAN","ISO Code":"AF"},
{"Country":"ALBANIA","ISO Code":"AL"},
{"Country":"ALGERIA","ISO Code":"DZ"},
{"Country":"AMERICAN SAMOA","ISO Code":"AS"},
{"Country":"ANDORRA","ISO Code":"AD"},
{"Country":"ANGOLA","ISO Code":"AO"},
{"Country":"ANTARCTICA (THE TERRITORY SOUTH OF 60 DEG S)","ISO Code":"AQ"},
{"Country":"ANTIGUA AND BARBUDA","ISO Code":"AG"},
{"Country":"ANGUILLA","ISO Code":"AI"},
{"Country":"ARGENTINA","ISO Code":"AR"},
{"Country":"ARMENIA","ISO Code":"AM"},
{"Country":"ARUBA","ISO Code":"AW"},
{"Country":"AUSTRALIA","ISO Code":"AU"},
{"Country":"AUSTRIA","ISO Code":"AT"},
{"Country":"AZERBAIJAN","ISO Code":"AZ"},
{"Country":"BAHAMAS","ISO Code":"BS"},
{"Country":"BAHRAIN","ISO Code":"BH"},
{"Country":"BANGLADESH","ISO Code":"BD"},
{"Country":"BARBADOS","ISO Code":"BB"},
{"Country":"BELARUS","ISO Code":"BY"},
{"Country":"BELGIUM","ISO Code":"BE"},
{"Country":"BELIZE","ISO Code":"BZ"},
{"Country":"BENIN","ISO Code":"BJ"},
{"Country":"BERMUDA","ISO Code":"BM"},
{"Country":"BHUTAN","ISO Code":"BT"},
{"Country":"BOLIVIA","ISO Code":"BO"},
{"Country":"BOSNIA AND HERZEGOVINA","ISO Code":"BA"},
{"Country":"BOTSWANA","ISO Code":"BW"},
{"Country":"BOUVET ISLAND (BOUVETOYA)","ISO Code":"BV"},
{"Country":"BRAZIL","ISO Code":"BR"},
{"Country":"BRITISH INDIAN OCEAN TERRITORY (CHAGOS ARCHIPELAGO)","ISO Code":"IO"},
{"Country":"BRUNEI DARUSSALAM","ISO Code":"BN"},
{"Country":"BULGARIA","ISO Code":"BG"},
{"Country":"BURKINA FASO","ISO Code":"BF"},
{"Country":"BURUNDI","ISO Code":"BI"},
{"Country":"CAMBODIA","ISO Code":"KH"},
{"Country":"CAMEROON","ISO Code":"CM"},
{"Country":"CANADA","ISO Code":"CA"},
{"Country":"CAPE VERDE","ISO Code":"CV"},
{"Country":"CAYMAN ISLANDS","ISO Code":"KY"},
{"Country":"CENTRAL AFRICAN REPUBLIC","ISO Code":"CF"},
{"Country":"CHAD","ISO Code":"TD"},
{"Country":"CHILE","ISO Code":"CL"},
{"Country":"CHINA","ISO Code":"CN"},
{"Country":"CHRISTMAS ISLAND","ISO Code":"CX"},
{"Country":"COCOS (KEELING) ISLANDS","ISO Code":"CC"},
{"Country":"COLOMBIA","ISO Code":"CO"},
{"Country":"COMOROS","ISO Code":"KM"},
{"Country":"CONGO","ISO Code":"CG"},
{"Country":"CONGO, THE DEMOCRATIC REPUBLIC OF THE","ISO Code":"CD"},
{"Country":"COOK ISLANDS","ISO Code":"CK"},
{"Country":"COSTA RICA","ISO Code":"CR"},
{"Country":"COTE D'IVOIRE","ISO Code":"CI"},
{"Country":"CROATIA","ISO Code":"HR"},
{"Country":"CUBA","ISO Code":"CU"},
{"Country":"CYPRUS","ISO Code":"CY"},
{"Country":"CZECH REPUBLIC","ISO Code":"CZ"},
{"Country":"DENMARK","ISO Code":"DK"},
{"Country":"DJIBOUTI","ISO Code":"DJ"},
{"Country":"DOMINICA","ISO Code":"DM"},
{"Country":"DOMINICAN REPUBLIC","ISO Code":"DO"},
{"Country":"ECUADOR","ISO Code":"EC"},
{"Country":"EGYPT","ISO Code":"EG"},
{"Country":"EL SALVADOR","ISO Code":"SV"},
{"Country":"EQUATORIAL GUINEA","ISO Code":"GQ"},
{"Country":"ERITREA","ISO Code":"ER"},
{"Country":"ESTONIA","ISO Code":"EE"},
{"Country":"ETHIOPIA","ISO Code":"ET"},
{"Country":"FALKLAND ISLANDS (MALVINAS)","ISO Code":"FK"},
{"Country":"FAROE ISLANDS","ISO Code":"FO"},
{"Country":"FIJI","ISO Code":"FJ"},
{"Country":"FINLAND","ISO Code":"FI"},
{"Country":"FRANCE","ISO Code":"FR"},
{"Country":"FRENCH GUIANA","ISO Code":"GF"},
{"Country":"FRENCH POLYNESIA","ISO Code":"PF"},
{"Country":"FRENCH SOUTHERN TERRITORIES","ISO Code":"TF"},
{"Country":"GABON","ISO Code":"GA"},
{"Country":"GAMBIA","ISO Code":"GM"},
{"Country":"GEORGIA","ISO Code":"GE"},
{"Country":"GERMANY","ISO Code":"DE"},
{"Country":"GHANA","ISO Code":"GH"},
{"Country":"GIBRALTAR","ISO Code":"GI"},
{"Country":"GREECE","ISO Code":"GR"},
{"Country":"GREENLAND","ISO Code":"GL"},
{"Country":"GRENADA","ISO Code":"GD"},
{"Country":"GUERNSEY","ISO Code":"GG"},
{"Country":"GUADELOUPE","ISO Code":"GP"},
{"Country":"GUAM","ISO Code":"GU"},
{"Country":"GUATEMALA","ISO Code":"GT"},
{"Country":"GUINEA","ISO Code":"GN"},
{"Country":"GUINEA-BISSAU","ISO Code":"GW"},
{"Country":"GUYANA","ISO Code":"GY"},
{"Country":"HAITI","ISO Code":"HT"},
{"Country":"HEARD ISLAND AND MCDONALD ISLANDS","ISO Code":"HM"},
{"Country":"HONDURAS","ISO Code":"HN"},
{"Country":"HONG KONG","ISO Code":"HK"},
{"Country":"HUNGARY","ISO Code":"HU"},
{"Country":"ICELAND","ISO Code":"IS"},
{"Country":"INDIA","ISO Code":"IN"},
{"Country":"INDONESIA","ISO Code":"ID"},
{"Country":"IRAN","ISO Code":"IR"},
{"Country":"IRAQ","ISO Code":"IQ"},
{"Country":"IRELAND","ISO Code":"IE"},
{"Country":"ISRAEL","ISO Code":"IL"},
{"Country":"ITALY","ISO Code":"IT"},
{"Country":"ISLE OF MAN","ISO Code":"IM"},
{"Country":"JAMAICA","ISO Code":"JM"},
{"Country":"JAPAN","ISO Code":"JP"},
{"Country":"JORDAN","ISO Code":"JO"},
{"Country":"JERSEY","ISO Code":"JE"},
{"Country":"KAZAKHSTAN","ISO Code":"KZ"},
{"Country":"KENYA","ISO Code":"KE"},
{"Country":"KIRIBATI","ISO Code":"KI"},
{"Country":"KOREA","ISO Code":"KR"},
{"Country":"KUWAIT","ISO Code":"KW"},
{"Country":"KYRGYZ REPUBLIC","ISO Code":"KG"},
{"Country":"LAO PEOPLE'S DEMOCRATIC REPUBLIC","ISO Code":"LA"},
{"Country":"LATVIA","ISO Code":"LV"},
{"Country":"LEBANON","ISO Code":"LB"},
{"Country":"LESOTHO","ISO Code":"LS"},
{"Country":"LIBERIA","ISO Code":"LR"},
{"Country":"LIBYAN ARAB JAMAHIRIYA","ISO Code":"LY"},
{"Country":"LIECHTENSTEIN","ISO Code":"LI"},
{"Country":"LITHUANIA","ISO Code":"LT"},
{"Country":"LUXEMBOURG","ISO Code":"LU"},
{"Country":"MACAO","ISO Code":"MO"},
{"Country":"MACEDONIA","ISO Code":"MK"},
{"Country":"MADAGASCAR","ISO Code":"MG"},
{"Country":"MALAWI","ISO Code":"MW"},
{"Country":"MALAYSIA","ISO Code":"MY"},
{"Country":"MALDIVES","ISO Code":"MV"},
{"Country":"MALI","ISO Code":"ML"},
{"Country":"MALTA","ISO Code":"MT"},
{"Country":"MARSHALL ISLANDS","ISO Code":"MH"},
{"Country":"MARTINIQUE","ISO Code":"MQ"},
{"Country":"MAURITANIA","ISO Code":"MR"},
{"Country":"MAURITIUS","ISO Code":"MU"},
{"Country":"MAYOTTE","ISO Code":"YT"},
{"Country":"MEXICO","ISO Code":"MX"},
{"Country":"MICRONESIA","ISO Code":"FM"},
{"Country":"MOLDOVA","ISO Code":"MD"},
{"Country":"MONACO","ISO Code":"MC"},
{"Country":"MONGOLIA","ISO Code":"MN"},
{"Country":"MONTENEGRO","ISO Code":"ME"},
{"Country":"MONTSERRAT","ISO Code":"MS"},
{"Country":"MOROCCO","ISO Code":"MA"},
{"Country":"MOZAMBIQUE","ISO Code":"MZ"},
{"Country":"MYANMAR","ISO Code":"MM"},
{"Country":"NAMIBIA","ISO Code":"NA"},
{"Country":"NAURU","ISO Code":"NR"},
{"Country":"NEPAL","ISO Code":"NP"},
{"Country":"NETHERLANDS","ISO Code":"NL"},
{"Country":"NETHERLANDS ANTILLES","ISO Code":"AN"},
{"Country":"NEW CALEDONIA","ISO Code":"NC"},
{"Country":"NEW ZEALAND","ISO Code":"NZ"},
{"Country":"NICARAGUA","ISO Code":"NI"},
{"Country":"NIGER","ISO Code":"NE"},
{"Country":"NIGERIA","ISO Code":"NG"},
{"Country":"NIUE","ISO Code":"NU"},
{"Country":"NORFOLK ISLAND","ISO Code":"NF"},
{"Country":"NORTHERN MARIANA ISLANDS","ISO Code":"MP"},
{"Country":"NORWAY","ISO Code":"NO"},
{"Country":"OMAN","ISO Code":"OM"},
{"Country":"PAKISTAN","ISO Code":"PK"},
{"Country":"PALAU","ISO Code":"PW"},
{"Country":"PALESTINIAN TERRITORIES","ISO Code":"PS"},
{"Country":"PANAMA","ISO Code":"PA"},
{"Country":"PAPUA NEW GUINEA","ISO Code":"PG"},
{"Country":"PARAGUAY","ISO Code":"PY"},
{"Country":"PERU","ISO Code":"PE"},
{"Country":"PHILIPPINES","ISO Code":"PH"},
{"Country":"PITCAIRN ISLANDS","ISO Code":"PN"},
{"Country":"POLAND","ISO Code":"PL"},
{"Country":"PORTUGAL","ISO Code":"PT"},
{"Country":"PUERTO RICO","ISO Code":"PR"},
{"Country":"QATAR","ISO Code":"QA"},
{"Country":"REUNION","ISO Code":"RE"},
{"Country":"ROMANIA","ISO Code":"RO"},
{"Country":"RUSSIAN FEDERATION","ISO Code":"RU"},
{"Country":"RWANDA","ISO Code":"RW"},
{"Country":"SAINT HELENA","ISO Code":"SH"},
{"Country":"SAINT KITTS AND NEVIS","ISO Code":"KN"},
{"Country":"SAINT LUCIA","ISO Code":"LC"},
{"Country":"SAINT PIERRE AND MIQUELON","ISO Code":"PM"},
{"Country":"SAINT BARTHELEMY","ISO Code":"BL"},
{"Country":"SAINT MARTIN","ISO Code":"SX"},
{"Country":"HOLY SEE (VATICAN CITY STATE)","ISO Code":"VA"},
{"Country":"SAINT VINCENT AND THE GRENADINES","ISO Code":"VC"},
{"Country":"SAMOA","ISO Code":"WS"},
{"Country":"SAN MARINO","ISO Code":"SM"},
{"Country":"SAO TOME AND PRINCIPE","ISO Code":"ST"},
{"Country":"SAUDI ARABIA","ISO Code":"SA"},
{"Country":"SENEGAL","ISO Code":"SN"},
{"Country":"SERBIA","ISO Code":"RS"},
{"Country":"SEYCHELLES","ISO Code":"SC"},
{"Country":"SIERRA LEONE","ISO Code":"SL"},
{"Country":"SINGAPORE","ISO Code":"SG"},
{"Country":"SLOVAKIA (SLOVAK REPUBLIC)","ISO Code":"SK"},
{"Country":"SLOVENIA","ISO Code":"SI"},
{"Country":"SOLOMON ISLANDS","ISO Code":"SB"},
{"Country":"SOMALIA","ISO Code":"SO"},
{"Country":"SOUTH AFRICA","ISO Code":"ZA"},
{"Country":"SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS","ISO Code":"GS"},
{"Country":"SOUTH SUDAN","ISO Code":"SS"},
{"Country":"SPAIN","ISO Code":"ES"},
{"Country":"SRI LANKA","ISO Code":"LK"},
{"Country":"SUDAN","ISO Code":"SD"},
{"Country":"SURINAME","ISO Code":"SR"},
{"Country":"SVALBARD & JAN MAYEN ISLANDS","ISO Code":"SJ"},
{"Country":"SWAZILAND","ISO Code":"SZ"},
{"Country":"SWEDEN","ISO Code":"SE"},
{"Country":"SWITZERLAND","ISO Code":"CH"},
{"Country":"SYRIAN ARAB REPUBLIC","ISO Code":"SY"},
{"Country":"TAIWAN","ISO Code":"TW"},
{"Country":"TAJIKISTAN","ISO Code":"TJ"},
{"Country":"TANZANIA","ISO Code":"TZ"},
{"Country":"THAILAND","ISO Code":"TH"},
{"Country":"TIMOR-LESTE","ISO Code":"TL"},
{"Country":"TOGO","ISO Code":"TG"},
{"Country":"TOKELAU","ISO Code":"TK"},
{"Country":"TONGA","ISO Code":"TO"},
{"Country":"TRINIDAD AND TOBAGO","ISO Code":"TT"},
{"Country":"TUNISIA","ISO Code":"TN"},
{"Country":"TURKEY","ISO Code":"TR"},
{"Country":"TURKMENISTAN","ISO Code":"TM"},
{"Country":"TURKS AND CAICOS ISLANDS","ISO Code":"TC"},
{"Country":"TUVALU","ISO Code":"TV"},
{"Country":"UGANDA","ISO Code":"UG"},
{"Country":"UKRAINE","ISO Code":"UA"},
{"Country":"UNITED ARAB EMIRATES","ISO Code":"AE"},
{"Country":"UNITED KINGDOM","ISO Code":"GB"},
{"Country":"UNITED STATES OF AMERICA","ISO Code":"US"},
{"Country":"UNITED STATES MINOR OUTLYING ISLANDS","ISO Code":"UM"},
{"Country":"URUGUAY","ISO Code":"UY"},
{"Country":"UZBEKISTAN","ISO Code":"UZ"},
{"Country":"VANUATU","ISO Code":"VU"},
{"Country":"VENEZUELA","ISO Code":"VE"},
{"Country":"VIETNAM","ISO Code":"VN"},
{"Country":"VIRGIN ISLANDS, BRITISH","ISO Code":"VG"},
{"Country":"UNITED STATES VIRGIN ISLANDS","ISO Code":"VI"},
{"Country":"WALLIS AND FUTUNA","ISO Code":"WF"},
{"Country":"WESTERN SAHARA","ISO Code":"EH"},
{"Country":"YEMEN","ISO Code":"YE"},
{"Country":"ZAMBIA","ISO Code":"ZM"},
{"Country":"ZIMBABWE","ISO Code":"ZW"}];